name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t tythos/tinytex-alpine:v2024.04 .

      - name: Push Docker image to Docker Hub
        run: docker push tythos/tinytex-alpine:v2024.04
